# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/design_xdc.xdc

# Block Designs: bd/Spi_interface_debug/Spi_interface_debug.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Spi_interface_debug || ORIG_REF_NAME==Spi_interface_debug} -quiet] -quiet

# IP: bd/Spi_interface_debug/ip/Spi_interface_debug_c_counter_binary_0_0/Spi_interface_debug_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Spi_interface_debug_c_counter_binary_0_0 || ORIG_REF_NAME==Spi_interface_debug_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/Spi_interface_debug/ip/Spi_interface_debug_xlconstant_0_0/Spi_interface_debug_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Spi_interface_debug_xlconstant_0_0 || ORIG_REF_NAME==Spi_interface_debug_xlconstant_0_0} -quiet] -quiet

# IP: bd/Spi_interface_debug/ip/Spi_interface_debug_ila_0_0/Spi_interface_debug_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Spi_interface_debug_ila_0_0 || ORIG_REF_NAME==Spi_interface_debug_ila_0_0} -quiet] -quiet

# IP: bd/Spi_interface_debug/ip/Spi_interface_debug_proc_sys_reset_0_0/Spi_interface_debug_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Spi_interface_debug_proc_sys_reset_0_0 || ORIG_REF_NAME==Spi_interface_debug_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Spi_interface_debug/ip/Spi_interface_debug_Top_Spi_Master_0_0/Spi_interface_debug_Top_Spi_Master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Spi_interface_debug_Top_Spi_Master_0_0 || ORIG_REF_NAME==Spi_interface_debug_Top_Spi_Master_0_0} -quiet] -quiet

# XDC: e:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Debuggin_various_IPs/Debuggin_various_IPs.gen/sources_1/bd/Spi_interface_debug/Spi_interface_debug_ooc.xdc
