# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Counter_debug/cnt_debug/cnt_debug.srcs/sources_1/bd/design_1/ip/design_1_c_counter_binary_0_0/design_1_c_counter_binary_0_0.xci
# IP: The module: 'design_1_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Counter_debug/cnt_debug/cnt_debug.gen/sources_1/bd/design_1/ip/design_1_c_counter_binary_0_0/design_1_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Counter_debug/cnt_debug/cnt_debug.srcs/sources_1/bd/design_1/ip/design_1_c_counter_binary_0_0/design_1_c_counter_binary_0_0.xci
# IP: The module: 'design_1_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Counter_debug/cnt_debug/cnt_debug.gen/sources_1/bd/design_1/ip/design_1_c_counter_binary_0_0/design_1_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
