# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Debuggin_various_IPs/Debuggin_various_IPs.srcs/sources_1/bd/Spi_interface_debug/ip/Spi_interface_debug_ila_0_0/Spi_interface_debug_ila_0_0.xci
# IP: The module: 'Spi_interface_debug_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Debuggin_various_IPs/Debuggin_various_IPs.gen/sources_1/bd/Spi_interface_debug/ip/Spi_interface_debug_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'Spi_interface_debug_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Debuggin_various_IPs/Debuggin_various_IPs.gen/sources_1/bd/Spi_interface_debug/ip/Spi_interface_debug_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'Spi_interface_debug_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Debuggin_various_IPs/Debuggin_various_IPs.gen/sources_1/bd/Spi_interface_debug/ip/Spi_interface_debug_ila_0_0/Spi_interface_debug_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Spi_interface_debug_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Debuggin_various_IPs/Debuggin_various_IPs.srcs/sources_1/bd/Spi_interface_debug/ip/Spi_interface_debug_ila_0_0/Spi_interface_debug_ila_0_0.xci
# IP: The module: 'Spi_interface_debug_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Debuggin_various_IPs/Debuggin_various_IPs.gen/sources_1/bd/Spi_interface_debug/ip/Spi_interface_debug_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'Spi_interface_debug_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Debuggin_various_IPs/Debuggin_various_IPs.gen/sources_1/bd/Spi_interface_debug/ip/Spi_interface_debug_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'Spi_interface_debug_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/VIVADO_2022/ARTIX_A7_FPGA/Debugging/Debugging_Xilinx_IPs/Debuggin_various_IPs/Debuggin_various_IPs.gen/sources_1/bd/Spi_interface_debug/ip/Spi_interface_debug_ila_0_0/Spi_interface_debug_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Spi_interface_debug_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
